### ISSUE TITLE
Feature: add post metadata

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/docs#21]
### Type of feature

Feature

### Current behavior

Anyone adding a new post or article is not officially credited outside of GitHub contributions

### Desired solution

Use metadata to add author information and other social links

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deadreyo** [comment]
Where exactly are these posts or articles? The docs website only displays documentation pages.

**Comment by 0-vortex** [comment]
> Where exactly are these posts or articles? The docs website only displays documentation pages.

Are you familiar with https://docusaurus.io/docs/markdown-features#front-matter ? We are using docusaurus to create the docs 🍕

**Comment by Deadreyo** [comment]
Yes I had a look on it. So you want the meta data on the "docs" pages right? What I initially understood is that there is a separate blog for posts or something.

**Comment by 0-vortex** [comment]
> Yes I had a look on it. So you want the meta data on the "docs" pages right? What I initially understood is that there is a separate blog for posts or something.

No, the issue was about making the "author" clickable as we only really have GitHub username authors - https://docusaurus.io/docs/blog#blog-post-authors sheds more light on the 2 ways to do it!

**Comment by Deadreyo** [comment]
> No, the issue was about making the "author" clickable as we only really have GitHub username authors - https://docusaurus.io/docs/blog#blog-post-authors sheds more light on the 2 ways to do it!

Is this the author section you're talking about?
![image](https://user-images.githubusercontent.com/52013393/192860505-4a193469-1f60-49ce-ba62-7bcc451081e1.png)
Because I can't find any other section for authors in the project https://docs.opensauced.pizza/

**Comment by huynhicode** [comment]
For the doc metadata, you can add something like this to the top of each md file:

```
---
id: head-metadata
title: Head Metadata
---
```

I am familiar with Docusaurus and wouldn't mind taking on this issue @0-vortex @Deadreyo

**Comment by Deadreyo** [comment]
> For the doc metadata, you can add something like this to the top of each md file:
> 
> ```
> ---
> id: head-metadata
> title: Head Metadata
> ---
> ```
> 
> I am familiar with Docusaurus and wouldn't mind taking on this issue @0-vortex @Deadreyo
> 
> Or maybe create a new issue for adding metadata? I think this issue is for blog authors specifically?

Yes this is a different issue. Here we're discussing modifying the "last updated" section to include a link to the author's profile.
Maybe this issue can be renamed to be more precise.

**Comment by Deadreyo** [comment]
Ok so I researched about it, and there doesn't seem to be a configurable supported way by the framework to get any more details about the author.

I've also asked on their github discussions, and got this message, which clarifies that they dont handle email adressess / profile links due to the mentioned reasons.

![image](https://user-images.githubusercontent.com/52013393/193278732-f1a08b10-bfc1-4583-8031-70846dce8624.png)

The suggested answer by the collaborator was to make an email / link field that would be manually filled by the author upon updating the page.

--------

Issues with this solution:
- last_update frontmatter is not supported in this version of docusaurus. Will have to update.
- The updater/author may forget to edit the link field, leading to names having wrong links.
- Of course the need to update a field, instead of currently just applying the content edits.
- Will require modification of the plugin-content-docs library

**Comment by huynhicode** [comment]
> > For the doc metadata, you can add something like this to the top of each md file:
> > ```
> > ---
> > id: head-metadata
> > title: Head Metadata
> > ---
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am familiar with Docusaurus and wouldn't mind taking on this issue @0-vortex @Deadreyo
> > Or maybe create a new issue for adding metadata? I think this issue is for blog authors specifically?
> 
> Yes this is a different issue. Here we're discussing modifying the "last updated" section to include a link to the author's profile. Maybe this issue can be renamed to be more precise.

I have created an issue: https://github.com/open-sauced/docs.opensauced.pizza/issues/45 and will work on adding and configuring the head metadata.

**Comment by CBID2** [comment]
Hey @0-vortex. Any update on this?
