### ISSUE TITLE
docs: Add "api.opensauced.pizza" category

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/docs#53]
### Type of feature

📝 Documentation

### Current behavior

Right now there is no category for the API project.

### Suggested solution

Make a new category for the api repo, and possibly make a new doc page in it called "Getting Started", which guides user through the installation and running the project (probably just clone the readme of the project, but without the extra steps that are not functioning like tests).

Adding the doc page so that the category would not be empty.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jeseekia** [comment]
.take

**Comment by jeseekia** [comment]
Hey! I am working on a PR for this, but wondering how you all might want some of the URLs from the repo README handled or whether you want to remove any of the existing documentation for the purposes of the Getting Started page. I started to add the missing images, but there are still broken links that I haven't fixed just yet. I was thinking some of these links might get tedious to update in order to stay in sync with the repository README file. Here are the lines in question:
https://github.com/jeseekia/docs.opensauced.pizza/blob/34b55590b970896a0eb0bc41bb0a470b2a966051/docs/apiOpensaucedPizza/getting-started.md?plain=1#L183
https://github.com/jeseekia/docs.opensauced.pizza/blob/34b55590b970896a0eb0bc41bb0a470b2a966051/docs/apiOpensaucedPizza/getting-started.md?plain=1#L200
https://github.com/jeseekia/docs.opensauced.pizza/blob/34b55590b970896a0eb0bc41bb0a470b2a966051/docs/apiOpensaucedPizza/getting-started.md?plain=1#L203

Any recommendations? I could remove these items, or just remove the URL, copy corresponding files over, or link to the files in the repo.

**Comment by diivi** [comment]
@jeseekia are you still working on this? If not, I'd like to try adding the documentation for api.opensauced.pizza

**Comment by bdougie** [comment]
Just unassigned.
