### ISSUE TITLE
Bug: download book link goes to 404

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/docs#97]
### Describe the bug

The download book link in the footer takes you to a 404

<img width="260" alt="image" src="https://github.com/open-sauced/docs/assets/34313413/770df54b-d98a-447e-ad5a-35f5ee683b1b">

### Steps to reproduce

1. Go to https://docs.opensauced.pizza
2. Click Download book
3. See 404

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Aysha-py** [comment]
Hello, it seems that the issue may be related to the provided link. If you could provide the correct link, I would be happy to work on this issue.

**Comment by bdougie** [comment]
> Hello, it seems that the issue may be related to the provided link. If you could provide the correct link, I would be happy to work on this issue.

It is a little more involved. We need to fix the release.yml to generate the PDF and place the link to file generated

More context here: https://dev.to/opensauced/generate-pdf-handbook-with-docusaurus-using-github-actions-lfb

**Comment by Aysha-py** [comment]
@bdougie, I just checked the article and I can see the workflow on the  release.yml file. It seems more advance than I thought.

**Comment by a0m0rajab** [comment]
The book is available and updated in the GitHub pages branch: https://github.com/open-sauced/docs/blob/gh-pages/open-sauced-docs.pdf

Not sure why it's not working on the deployed static website, It worked locally though. @bdougie if you are okay, we can change the link to the GitHub Repo which could be a hotfix right now, unless you prefer to debug it. 

Here is the code that might be needed to change: 
https://github.com/open-sauced/docs/blob/3ed60beaffe4d034d6986f09d8a51781ec4b5774/docusaurus.config.js#L121-L122

**Comment by bdougie** [comment]
Just taking the link works perfect.

**Comment by bdougie** [comment]
Just updating the link actually won't work since the pdf gets generated on demand every time the site is deployed.

TBH, this experience is not needed and the whole feature can just be deleted.

Having a working pdf download would be great, but there is probably a low of people that would need this.

**Comment by a0m0rajab** [comment]
Oh, the PDF is being generated on demand by the way, but it's not on the website. 
The one we have right now is built on the last update: 
![image](https://github.com/open-sauced/docs/assets/18273833/65a4466e-b41e-4952-8cde-aae2605bd5be)

did a quick search and I think the issue is related to SPA nature: 
https://docusaurus.io/docs/next/advanced/routing#escaping-from-spa-redirects

**Comment by a0m0rajab** [comment]
Did another check we can solve this if we moved the pdf file to assets folder: 
https://github.com/facebook/docusaurus/issues/3337
https://docusaurus.io/docs/markdown-features/assets

we need to change this line for that: 
https://github.com/open-sauced/docs/blob/a023fc14567d2e17cf0f3c074a953374dfb9bfcb/package.json#L22

This is the related docs for docusaurus: 
https://github.com/signcl/docusaurus-prince-pdf

**Comment by a0m0rajab** [comment]
.take
